LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. Organisation information", "cy": ""},
            "tree_path": "1073.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Organisation information", "cy": ""},
            "tree_path": "1073.1.1.1",
            "form_name_json": {"en": "nwp-pill4-organisation-information", "cy": ""},
        },
        {
            "section_name": {"en": "2. Applicant information", "cy": ""},
            "tree_path": "1073.1.2",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "2.1 Applicant information", "cy": ""},
            "tree_path": "1073.1.2.1",
            "form_name_json": {"en": "nwp-pill4-applicant-information", "cy": ""},
        },
        {
            "section_name": {"en": "3. Skills and experience", "cy": ""},
            "tree_path": "1073.1.3",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "3.1 Skills and experience", "cy": ""},
            "tree_path": "1073.1.3.1",
            "form_name_json": {"en": "nwp-pill4-skills-and-experience", "cy": ""},
        },
        {"section_name": {"en": "4. Proposal", "cy": ""}, "tree_path": "1073.1.4", "requires_feedback": None},
        {
            "section_name": {"en": "4.1 Proposal", "cy": ""},
            "tree_path": "1073.1.4.1",
            "form_name_json": {"en": "nwp-pill4-proposal", "cy": ""},
        },
        {
            "section_name": {"en": "5. Outcomes and outputs", "cy": ""},
            "tree_path": "1073.1.5",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "5.1 Outputs and outcomes", "cy": ""},
            "tree_path": "1073.1.5.1",
            "form_name_json": {"en": "nwp-pill4-outputs-and-outcomes", "cy": ""},
        },
        {
            "section_name": {"en": "6. Cost and value for money", "cy": ""},
            "tree_path": "1073.1.6",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "6.1 Cost and value for money", "cy": ""},
            "tree_path": "1073.1.6.1",
            "form_name_json": {"en": "nwp-pill4-cost-and-value-for-money", "cy": ""},
        },
        {"section_name": {"en": "7. Stakeholders", "cy": ""}, "tree_path": "1073.1.7", "requires_feedback": None},
        {
            "section_name": {"en": "7.1 Stakeholders", "cy": ""},
            "tree_path": "1073.1.7.1",
            "form_name_json": {"en": "nwp-pill4-stakeholders", "cy": ""},
        },
        {"section_name": {"en": "8. Risks", "cy": ""}, "tree_path": "1073.1.8", "requires_feedback": None},
        {
            "section_name": {"en": "8.1 Risks", "cy": ""},
            "tree_path": "1073.1.8.1",
            "form_name_json": {"en": "nwp-pill4-risks", "cy": ""},
        },
        {"section_name": {"en": "9. Declaration", "cy": ""}, "tree_path": "1073.1.9", "requires_feedback": None},
        {
            "section_name": {"en": "9.1 Declaration", "cy": ""},
            "tree_path": "1073.1.9.1",
            "form_name_json": {"en": "nwp-pill4-declaration", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "44676f65-616d-4819-af7a-a457f693f008",
        "short_name": "NWP",
        "welsh_available": False,
        "ggis_scheme_reference_number": "G2-SCH-2025-10-17200",
        "funding_type": "COMPETITIVE",
        "owner_organisation_name": "",
        "owner_organisation_shortname": "",
        "owner_organisation_logo_uri": "",
        "name_json": {"en": "National Workforce Programme", "cy": ""},
        "title_json": {
            "en": "funding to develop the expertise, skills and capacity of the homelessness workforce",
            "cy": "",
        },
        "description_json": {
            "en": "A national workforce programme to help the frontline homeless workforce in England to develop expertise, skills and capacity. ",
            "cy": "",
        },
    },
    "round_config": {
        "id": "7f7fb87b-7336-4c2a-b83c-98c7830e835c",
        "fund_id": "44676f65-616d-4819-af7a-a457f693f008",
        "short_name": "Pill4",
        # "opens": "2025-11-10T12:00:00",
        "opens": "2025-11-10T12:00:00",
        # "assessment_start": "2025-12-09T09:00:00",
        "assessment_start": "2025-12-09T09:00:00",
        "deadline": "2025-12-08T17:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2025-12-01T12:00:00",
        "assessment_deadline": "2025-12-22T12:00:00",
        "prospectus": "https://www.gov.uk/government/publications/national-workforce-programme-prospectus",
        "privacy_notice": "www.notgotityet.com",
        "contact_email": "nwpgrant@communities.gov.uk",
        "instructions_json": {"en": None, "cy": None},
        "feedback_link": "",
        "project_name_field_id": "GtoolQ",
        "application_guidance_json": {
            "en": "<p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p>",
            "cy": None,
        },
        "guidance_url": "",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": True,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": False,
            "has_research_survey": False,
            "is_feedback_survey_optional": True,
            "is_section_feedback_optional": False,
            "is_research_survey_optional": True,
        },
        "eligibility_config": {"has_eligibility": True},
        "title_json": {"en": "Pillar 4 Community", "cy": None},
    },
    "base_path": 1073,
}
